name: flutter_kernel_transformers
version: 0.0.1-dev
description: Kernel transformers that operate on Flutter source code.
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

dependencies:
  kernel: any
  meta: any

dev_dependencies:
  test: any
  when: any

dependency_overrides:
  args:
    path: ../../third_party/dart/third_party/pkg/args
  async:
    path: ../../third_party/dart/third_party/pkg/async
  charcode:
    path: ../../third_party/dart/third_party/pkg/charcode
  collection:
    path: ../../third_party/dart/third_party/pkg/collection
  convert:
    path: ../../third_party/dart/third_party/pkg/convert
  crypto:
    path: ../../third_party/dart/third_party/pkg/crypto
  front_end:
    path: ../../third_party/dart/pkg/front_end/
  kernel:
    path: ../../third_party/dart/pkg/kernel/
  logging:
    path: ../../third_party/dart/third_party/pkg/logging
  meta:
    path: ../../third_party/dart/pkg/meta
  quiver:
    path: ../../third_party/dart/third_party/pkg/quiver
  package_config:
    path: ../../third_party/dart/third_party/pkg_tested/package_config
  path:
    path: ../../third_party/dart/third_party/pkg/path
  source_span:
    path: ../../third_party/dart/third_party/pkg/source_span
  typed_data:
    path: ../../third_party/dart/third_party/pkg/typed_data
  usage:
    path: ../../third_party/dart/third_party/pkg/usage
  vm:
    path: ../../third_party/dart/pkg/vm/

  analyzer:
    path: ../../third_party/dart/pkg/analyzer
  barback:
    path: ../../third_party/dart/third_party/pkg/barback
  boolean_selector:
    path: ../../third_party/dart/third_party/pkg/boolean_selector
  cli_util:
    path: ../../third_party/dart/third_party/pkg/cli_util
  csslib:
    path: ../../third_party/dart/third_party/pkg/csslib
  glob:
    path: ../../third_party/dart/third_party/pkg/glob
  html:
    path: ../../third_party/dart/third_party/pkg/html
  http:
    path: ../../third_party/dart/third_party/pkg/http
  http_multi_server:
    path: ../../third_party/dart/third_party/pkg/http_multi_server
  http_parser:
    path: ../../third_party/dart/third_party/pkg/http_parser
  matcher:
    path: ../../third_party/dart/third_party/pkg/matcher
  mime:
    path: ../../third_party/dart/third_party/pkg/mime
  mockito:
    path: ../../third_party/dart/third_party/pkg/mockito
  package_resolver:
    path: ../../third_party/dart/third_party/pkg_tested/package_resolver
  plugin:
    path: ../../third_party/dart/third_party/pkg/plugin
  pool:
    path: ../../third_party/dart/third_party/pkg/pool
  pub_semver:
    path: ../../third_party/dart/third_party/pkg/pub_semver
  shelf:
    path: ../../third_party/dart/third_party/pkg/shelf
  shelf_packages_handler:
    path: ../../third_party/dart/third_party/pkg/shelf_packages_handler
  shelf_static:
    path: ../../third_party/dart/third_party/pkg/shelf_static
  shelf_web_socket:
    path: ../../third_party/dart/third_party/pkg/shelf_web_socket
  source_map_stack_trace:
    path: ../../third_party/dart/third_party/pkg/source_map_stack_trace
  source_maps:
    path: ../../third_party/dart/third_party/pkg/source_maps
  stack_trace:
    path: ../../third_party/dart/third_party/pkg/stack_trace
  stream_channel:
    path: ../../third_party/dart/third_party/pkg/stream_channel
  string_scanner:
    path: ../../third_party/dart/third_party/pkg/string_scanner
  test:
    path: ../../third_party/dart/third_party/pkg/test
  utf:
    path: ../../third_party/dart/third_party/pkg/utf
  watcher:
    path: ../../third_party/dart/third_party/pkg/watcher
  web_socket_channel:
    path: ../../third_party/dart/third_party/pkg/web_socket_channel
  when:
    path: ../../third_party/pkg/when
  yaml:
    path: ../../third_party/dart/third_party/pkg/yaml
