name: workbench
version: 0.0.1
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A workspace to host pub packages
homepage: https://github.com/flutter/engine/tree/master/sky/packages/workbench
dependencies:
  flutter: 
    '0.0.16'
  sky_tools: any
  cipher: any
  asn1lib: any
  flutter_rendering_examples: any
  flutter_sprites: 
    '0.0.13'
  playfair: any
  flx: 
    '0.0.5'
dependency_overrides:
  material_design_icons:
    path: ../material_design_icons
  flutter:
    path: ../sky
  flutter_rendering_examples:
    path: ../../../examples/rendering
  flutter_sprites:
    path: ../../../skysprites
  flx:
    path: ../flx
environment:
  sdk: '>=1.8.0 <2.0.0'
