name: updater
author: Flutter Authors <flutter-dev@googlegroups.com>
description: The autoupdater for flutter
homepage: http://flutter.io
dependencies:
  mojo: 0.3.0
  flutter: 
    '0.0.16'
  sky_services: ^0.0.40
  yaml: ^2.1.3
  path: ^1.3.0
  flx: 0.0.1
  flutter_sprites:
    '0.0.13'
dependency_overrides:
  flutter:
    path: ../sky
  flx:
    path: ../flx
environment:
  sdk: '>=1.12.0 <2.0.0'
