name: flx
version: 0.0.9
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Library for dealing with Flutter bundle (.flx) files
homepage: http://flutter.io
dependencies:
  sky_services: 
    '0.0.48'
  yaml: ^2.1.3
  asn1lib: ^0.4.1
  cipher: ^0.7.1
  crypto: ^0.9.1
  path: ^1.3.0
environment:
  sdk: '>=1.12.0 <2.0.0'
